from __future__ import annotations

from math import floor
from typing import Any


LTE_CHANNEL_SPACING_MHZ = 0.1
MAX_CHANNEL_OFFSET_MHZ = 0.05


# Data diambil dari tabel LTE frequency band 36.101 (Rel 19 Jun 2025)
# yang dikirim dari Sqimway. Versi awal classifier ini melakukan
# pencocokan berdasarkan range frekuensi dan menghitung EARFCN terdekat.
#
# Catatan penting:
# - Hasil adalah kandidat berdasarkan frekuensi, bukan bukti sinyal LTE.
# - FDD dicek sebagai DL dan UL, karena satu frekuensi bisa cocok sebagai
#   downlink di satu band dan uplink di band lain.
# - TDD memakai satu range frekuensi bersama.
# - SDL ditandai sebagai downlink only.
LTE_BANDS: list[dict[str, Any]] = [{'band': '1',
  'bandwidth_mhz': '60',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 599,
  'dl_earfcn_low': 0,
  'dl_high_mhz': 2170.0,
  'dl_low_mhz': 2110.0,
  'duplex_spacing_mhz': 190.0,
  'geographical_area': 'Global',
  'mode': 'FDD',
  'name': '2100',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 18599,
  'ul_earfcn_low': 18000,
  'ul_high_mhz': 1980.0,
  'ul_low_mhz': 1920.0},
 {'band': '2',
  'bandwidth_mhz': '60',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 1199,
  'dl_earfcn_low': 600,
  'dl_high_mhz': 1990.0,
  'dl_low_mhz': 1930.0,
  'duplex_spacing_mhz': 80.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '1900 PCS',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 19199,
  'ul_earfcn_low': 18600,
  'ul_high_mhz': 1910.0,
  'ul_low_mhz': 1850.0},
 {'band': '3',
  'bandwidth_mhz': '75',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 1949,
  'dl_earfcn_low': 1200,
  'dl_high_mhz': 1880.0,
  'dl_low_mhz': 1805.0,
  'duplex_spacing_mhz': 95.0,
  'geographical_area': 'Global',
  'mode': 'FDD',
  'name': '1800+',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 19949,
  'ul_earfcn_low': 19200,
  'ul_high_mhz': 1785.0,
  'ul_low_mhz': 1710.0},
 {'band': '4',
  'bandwidth_mhz': '45',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 2399,
  'dl_earfcn_low': 1950,
  'dl_high_mhz': 2155.0,
  'dl_low_mhz': 2110.0,
  'duplex_spacing_mhz': 400.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': 'AWS-1',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 20399,
  'ul_earfcn_low': 19950,
  'ul_high_mhz': 1755.0,
  'ul_low_mhz': 1710.0},
 {'band': '5',
  'bandwidth_mhz': '25',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 2649,
  'dl_earfcn_low': 2400,
  'dl_high_mhz': 894.0,
  'dl_low_mhz': 869.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '850',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 20649,
  'ul_earfcn_low': 20400,
  'ul_high_mhz': 849.0,
  'ul_low_mhz': 824.0},
 {'band': '6',
  'bandwidth_mhz': '10',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 2749,
  'dl_earfcn_low': 2650,
  'dl_high_mhz': 885.0,
  'dl_low_mhz': 875.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'APAC',
  'mode': 'FDD',
  'name': '850 Japan',
  'note': 'Not applicable',
  'release': '8',
  'ul_earfcn_high': 20749,
  'ul_earfcn_low': 20650,
  'ul_high_mhz': 840.0,
  'ul_low_mhz': 830.0},
 {'band': '7',
  'bandwidth_mhz': '70',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 3449,
  'dl_earfcn_low': 2750,
  'dl_high_mhz': 2690.0,
  'dl_low_mhz': 2620.0,
  'duplex_spacing_mhz': 120.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '2600',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 21449,
  'ul_earfcn_low': 20750,
  'ul_high_mhz': 2570.0,
  'ul_low_mhz': 2500.0},
 {'band': '8',
  'bandwidth_mhz': '35',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 3799,
  'dl_earfcn_low': 3450,
  'dl_high_mhz': 960.0,
  'dl_low_mhz': 925.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'Global',
  'mode': 'FDD',
  'name': '900 GSM',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 21799,
  'ul_earfcn_low': 21450,
  'ul_high_mhz': 915.0,
  'ul_low_mhz': 880.0},
 {'band': '9',
  'bandwidth_mhz': '35',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 4149,
  'dl_earfcn_low': 3800,
  'dl_high_mhz': 1879.9,
  'dl_low_mhz': 1844.9,
  'duplex_spacing_mhz': 95.0,
  'geographical_area': 'APAC',
  'mode': 'FDD',
  'name': '1800',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 22149,
  'ul_earfcn_low': 21800,
  'ul_high_mhz': 1784.9,
  'ul_low_mhz': 1749.9},
 {'band': '10',
  'bandwidth_mhz': '60',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 4749,
  'dl_earfcn_low': 4150,
  'dl_high_mhz': 2170.0,
  'dl_low_mhz': 2110.0,
  'duplex_spacing_mhz': 400.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': 'AWS-3',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 22749,
  'ul_earfcn_low': 22150,
  'ul_high_mhz': 1770.0,
  'ul_low_mhz': 1710.0},
 {'band': '11',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 4949,
  'dl_earfcn_low': 4750,
  'dl_high_mhz': 1495.9,
  'dl_low_mhz': 1475.9,
  'duplex_spacing_mhz': 48.0,
  'geographical_area': 'Japan',
  'mode': 'FDD',
  'name': '1500 Lower',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 22949,
  'ul_earfcn_low': 22750,
  'ul_high_mhz': 1447.9,
  'ul_low_mhz': 1427.9},
 {'band': '12',
  'bandwidth_mhz': '17',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 5179,
  'dl_earfcn_low': 5010,
  'dl_high_mhz': 746.0,
  'dl_low_mhz': 729.0,
  'duplex_spacing_mhz': 30.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '700 a',
  'note': None,
  'release': '8.4',
  'ul_earfcn_high': 23179,
  'ul_earfcn_low': 23010,
  'ul_high_mhz': 716.0,
  'ul_low_mhz': 699.0},
 {'band': '13',
  'bandwidth_mhz': '10',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 5279,
  'dl_earfcn_low': 5180,
  'dl_high_mhz': 756.0,
  'dl_low_mhz': 746.0,
  'duplex_spacing_mhz': -31.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '700 c',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 23279,
  'ul_earfcn_low': 23180,
  'ul_high_mhz': 787.0,
  'ul_low_mhz': 777.0},
 {'band': '14',
  'bandwidth_mhz': '10',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 5379,
  'dl_earfcn_low': 5280,
  'dl_high_mhz': 768.0,
  'dl_low_mhz': 758.0,
  'duplex_spacing_mhz': -30.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '700 PS',
  'note': None,
  'release': '8',
  'ul_earfcn_high': 23379,
  'ul_earfcn_low': 23280,
  'ul_high_mhz': 798.0,
  'ul_low_mhz': 788.0},
 {'band': '17',
  'bandwidth_mhz': '12',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 5849,
  'dl_earfcn_low': 5730,
  'dl_high_mhz': 746.0,
  'dl_low_mhz': 734.0,
  'duplex_spacing_mhz': 30.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '700 b',
  'note': None,
  'release': '8.3',
  'ul_earfcn_high': 23849,
  'ul_earfcn_low': 23730,
  'ul_high_mhz': 716.0,
  'ul_low_mhz': 704.0},
 {'band': '18',
  'bandwidth_mhz': '15',
  'channel_bandwidths_mhz': [5, 10, 15],
  'dl_earfcn_high': 5999,
  'dl_earfcn_low': 5850,
  'dl_high_mhz': 875.0,
  'dl_low_mhz': 860.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'Japan',
  'mode': 'FDD',
  'name': '800 Lower',
  'note': None,
  'release': '9',
  'ul_earfcn_high': 23999,
  'ul_earfcn_low': 23850,
  'ul_high_mhz': 830.0,
  'ul_low_mhz': 815.0},
 {'band': '19',
  'bandwidth_mhz': '15',
  'channel_bandwidths_mhz': [5, 10, 15],
  'dl_earfcn_high': 6149,
  'dl_earfcn_low': 6000,
  'dl_high_mhz': 890.0,
  'dl_low_mhz': 875.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'Japan',
  'mode': 'FDD',
  'name': '800 Upper',
  'note': None,
  'release': '9',
  'ul_earfcn_high': 24149,
  'ul_earfcn_low': 24000,
  'ul_high_mhz': 845.0,
  'ul_low_mhz': 830.0},
 {'band': '20',
  'bandwidth_mhz': '30',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 6449,
  'dl_earfcn_low': 6150,
  'dl_high_mhz': 821.0,
  'dl_low_mhz': 791.0,
  'duplex_spacing_mhz': -41.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '800 DD',
  'note': None,
  'release': '9',
  'ul_earfcn_high': 24449,
  'ul_earfcn_low': 24150,
  'ul_high_mhz': 862.0,
  'ul_low_mhz': 832.0},
 {'band': '21',
  'bandwidth_mhz': '15',
  'channel_bandwidths_mhz': [5, 10, 15],
  'dl_earfcn_high': 6599,
  'dl_earfcn_low': 6450,
  'dl_high_mhz': 1510.9,
  'dl_low_mhz': 1495.9,
  'duplex_spacing_mhz': 48.0,
  'geographical_area': 'Japan',
  'mode': 'FDD',
  'name': '1500 Upper',
  'note': None,
  'release': '9',
  'ul_earfcn_high': 24599,
  'ul_earfcn_low': 24450,
  'ul_high_mhz': 1462.9,
  'ul_low_mhz': 1447.9},
 {'band': '22',
  'bandwidth_mhz': '80',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 7399,
  'dl_earfcn_low': 6600,
  'dl_high_mhz': 3590.0,
  'dl_low_mhz': 3510.0,
  'duplex_spacing_mhz': 100.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '3500',
  'note': None,
  'release': '10.4',
  'ul_earfcn_high': 25399,
  'ul_earfcn_low': 24600,
  'ul_high_mhz': 3490.0,
  'ul_low_mhz': 3410.0},
 {'band': '23',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 7699,
  'dl_earfcn_low': 7500,
  'dl_high_mhz': 2200.0,
  'dl_low_mhz': 2180.0,
  'duplex_spacing_mhz': 180.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '2000 S-band',
  'note': 'Not applicable',
  'release': '10.3',
  'ul_earfcn_high': 25699,
  'ul_earfcn_low': 25500,
  'ul_high_mhz': 2020.0,
  'ul_low_mhz': 2000.0},
 {'band': '24',
  'bandwidth_mhz': '34',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 8039,
  'dl_earfcn_low': 7700,
  'dl_high_mhz': 1559.0,
  'dl_low_mhz': 1525.0,
  'duplex_spacing_mhz': -101.5,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '1600 L-band',
  'note': None,
  'release': '10.1',
  'ul_earfcn_high': 26039,
  'ul_earfcn_low': 25700,
  'ul_high_mhz': 1660.5,
  'ul_low_mhz': 1626.5},
 {'band': '25',
  'bandwidth_mhz': '65',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 8689,
  'dl_earfcn_low': 8040,
  'dl_high_mhz': 1995.0,
  'dl_low_mhz': 1930.0,
  'duplex_spacing_mhz': 80.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '1900+',
  'note': None,
  'release': '10',
  'ul_earfcn_high': 26689,
  'ul_earfcn_low': 26040,
  'ul_high_mhz': 1915.0,
  'ul_low_mhz': 1850.0},
 {'band': '26',
  'bandwidth_mhz': '35',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15],
  'dl_earfcn_high': 9039,
  'dl_earfcn_low': 8690,
  'dl_high_mhz': 894.0,
  'dl_low_mhz': 859.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '850+',
  'note': None,
  'release': '11.0',
  'ul_earfcn_high': 27039,
  'ul_earfcn_low': 26690,
  'ul_high_mhz': 849.0,
  'ul_low_mhz': 814.0},
 {'band': '27',
  'bandwidth_mhz': '17',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 9209,
  'dl_earfcn_low': 9040,
  'dl_high_mhz': 869.0,
  'dl_low_mhz': 852.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '800 SMR',
  'note': None,
  'release': '11.1',
  'ul_earfcn_high': 27209,
  'ul_earfcn_low': 27040,
  'ul_high_mhz': 824.0,
  'ul_low_mhz': 807.0},
 {'band': '28',
  'bandwidth_mhz': '45',
  'channel_bandwidths_mhz': [3, 5, 10, 15, 20],
  'dl_earfcn_high': 9659,
  'dl_earfcn_low': 9210,
  'dl_high_mhz': 803.0,
  'dl_low_mhz': 758.0,
  'duplex_spacing_mhz': 55.0,
  'geographical_area': 'APAC, EU',
  'mode': 'FDD',
  'name': '700 APT',
  'note': None,
  'release': '11.1',
  'ul_earfcn_high': 27659,
  'ul_earfcn_low': 27210,
  'ul_high_mhz': 748.0,
  'ul_low_mhz': 703.0},
 {'band': '29',
  'bandwidth_mhz': '11',
  'channel_bandwidths_mhz': [3, 5, 10],
  'dl_earfcn_high': 9769,
  'dl_earfcn_low': 9660,
  'dl_high_mhz': 728.0,
  'dl_low_mhz': 717.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'NAR',
  'mode': 'SDL',
  'name': '700 d',
  'note': 'CA',
  'release': '11.3',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '30',
  'bandwidth_mhz': '10',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 9869,
  'dl_earfcn_low': 9770,
  'dl_high_mhz': 2360.0,
  'dl_low_mhz': 2350.0,
  'duplex_spacing_mhz': 45.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '2300 WCS',
  'note': None,
  'release': '12.0',
  'ul_earfcn_high': 27759,
  'ul_earfcn_low': 27660,
  'ul_high_mhz': 2315.0,
  'ul_low_mhz': 2305.0},
 {'band': '31',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 9919,
  'dl_earfcn_low': 9870,
  'dl_high_mhz': 467.5,
  'dl_low_mhz': 462.5,
  'duplex_spacing_mhz': 10.0,
  'geographical_area': 'Global',
  'mode': 'FDD',
  'name': '450',
  'note': None,
  'release': '12.0',
  'ul_earfcn_high': 27809,
  'ul_earfcn_low': 27760,
  'ul_high_mhz': 457.5,
  'ul_low_mhz': 452.5},
 {'band': '32',
  'bandwidth_mhz': '44',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 10359,
  'dl_earfcn_low': 9920,
  'dl_high_mhz': 1496.0,
  'dl_low_mhz': 1452.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EMEA',
  'mode': 'SDL',
  'name': '1500 L-band',
  'note': 'CA',
  'release': '12.4',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '33',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 36199,
  'dl_earfcn_low': 36000,
  'dl_high_mhz': 1920.0,
  'dl_low_mhz': 1900.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EMEA',
  'mode': 'TDD',
  'name': 'TD 1900',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '34',
  'bandwidth_mhz': '15',
  'channel_bandwidths_mhz': [5, 10, 15],
  'dl_earfcn_high': 36349,
  'dl_earfcn_low': 36200,
  'dl_high_mhz': 2025.0,
  'dl_low_mhz': 2010.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EMEA',
  'mode': 'TDD',
  'name': 'TD 2000',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '35',
  'bandwidth_mhz': '60',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 36949,
  'dl_earfcn_low': 36350,
  'dl_high_mhz': 1910.0,
  'dl_low_mhz': 1850.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'NAR',
  'mode': 'TDD',
  'name': 'TD PCS Lower',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '36',
  'bandwidth_mhz': '60',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 37549,
  'dl_earfcn_low': 36950,
  'dl_high_mhz': 1990.0,
  'dl_low_mhz': 1930.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'NAR',
  'mode': 'TDD',
  'name': 'TD PCS Upper',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '37',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 37749,
  'dl_earfcn_low': 37550,
  'dl_high_mhz': 1930.0,
  'dl_low_mhz': 1910.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'NAR',
  'mode': 'TDD',
  'name': 'TD PCS Center gap',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '38',
  'bandwidth_mhz': '50',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 38249,
  'dl_earfcn_low': 37750,
  'dl_high_mhz': 2620.0,
  'dl_low_mhz': 2570.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EMEA',
  'mode': 'TDD',
  'name': 'TD 2600',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '39',
  'bandwidth_mhz': '40',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 38649,
  'dl_earfcn_low': 38250,
  'dl_high_mhz': 1920.0,
  'dl_low_mhz': 1880.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'China',
  'mode': 'TDD',
  'name': 'TD 1900+',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '40',
  'bandwidth_mhz': '100',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 39649,
  'dl_earfcn_low': 38650,
  'dl_high_mhz': 2400.0,
  'dl_low_mhz': 2300.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'China',
  'mode': 'TDD',
  'name': 'TD 2300',
  'note': None,
  'release': '8',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '41',
  'bandwidth_mhz': '194',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 41589,
  'dl_earfcn_low': 39650,
  'dl_high_mhz': 2690.0,
  'dl_low_mhz': 2496.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'Global',
  'mode': 'TDD',
  'name': 'TD 2600+',
  'note': None,
  'release': '10',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '42',
  'bandwidth_mhz': '200',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 43589,
  'dl_earfcn_low': 41590,
  'dl_high_mhz': 3600.0,
  'dl_low_mhz': 3400.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'TDD',
  'name': 'TD 3500',
  'note': None,
  'release': '10',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '43',
  'bandwidth_mhz': '200',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 45589,
  'dl_earfcn_low': 43590,
  'dl_high_mhz': 3800.0,
  'dl_low_mhz': 3600.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'TDD',
  'name': 'TD 3700',
  'note': None,
  'release': '10',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '44',
  'bandwidth_mhz': '100',
  'channel_bandwidths_mhz': [3, 5, 10, 15, 20],
  'dl_earfcn_high': 46589,
  'dl_earfcn_low': 45590,
  'dl_high_mhz': 803.0,
  'dl_low_mhz': 703.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'APAC',
  'mode': 'TDD',
  'name': 'TD 700',
  'note': None,
  'release': '11.1',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '45',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 46789,
  'dl_earfcn_low': 46590,
  'dl_high_mhz': 1467.0,
  'dl_low_mhz': 1447.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'China',
  'mode': 'TDD',
  'name': 'TD 1500',
  'note': None,
  'release': '13.2',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '46',
  'bandwidth_mhz': '775',
  'channel_bandwidths_mhz': [10, 20],
  'dl_earfcn_high': 54539,
  'dl_earfcn_low': 46790,
  'dl_high_mhz': 5925.0,
  'dl_low_mhz': 5150.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'Global',
  'mode': 'TDD',
  'name': 'TD Unlicensed',
  'note': None,
  'release': '13.2',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '47',
  'bandwidth_mhz': '70',
  'channel_bandwidths_mhz': [10, 20],
  'dl_earfcn_high': 55239,
  'dl_earfcn_low': 54540,
  'dl_high_mhz': 5925.0,
  'dl_low_mhz': 5855.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'Global',
  'mode': 'TDD',
  'name': 'TD V2X',
  'note': None,
  'release': '14.1',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '48',
  'bandwidth_mhz': '150',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 56739,
  'dl_earfcn_low': 55240,
  'dl_high_mhz': 3700.0,
  'dl_low_mhz': 3550.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'Global',
  'mode': 'TDD',
  'name': 'TD 3600',
  'note': None,
  'release': '14.2',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '49',
  'bandwidth_mhz': '150',
  'channel_bandwidths_mhz': [10, 20],
  'dl_earfcn_high': 58239,
  'dl_earfcn_low': 56740,
  'dl_high_mhz': 3700.0,
  'dl_low_mhz': 3550.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'Global',
  'mode': 'TDD',
  'name': 'TD 3600r',
  'note': None,
  'release': '15.1',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '50',
  'bandwidth_mhz': '85',
  'channel_bandwidths_mhz': [3, 5, 10, 15, 20],
  'dl_earfcn_high': 59089,
  'dl_earfcn_low': 58240,
  'dl_high_mhz': 1517.0,
  'dl_low_mhz': 1432.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EU',
  'mode': 'TDD',
  'name': 'TD 1500+',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '51',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [3, 5],
  'dl_earfcn_high': 59139,
  'dl_earfcn_low': 59090,
  'dl_high_mhz': 1432.0,
  'dl_low_mhz': 1427.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EU',
  'mode': 'TDD',
  'name': 'TD 1500-',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '52',
  'bandwidth_mhz': '100',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 60139,
  'dl_earfcn_low': 59140,
  'dl_high_mhz': 3400.0,
  'dl_low_mhz': 3300.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'TDD',
  'name': 'TD 3300',
  'note': None,
  'release': '15.2',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '53',
  'bandwidth_mhz': '11.5',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 60254,
  'dl_earfcn_low': 60140,
  'dl_high_mhz': 2495.0,
  'dl_low_mhz': 2483.5,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'TDD',
  'name': 'TD 2500',
  'note': None,
  'release': '16.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '54',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 60304,
  'dl_earfcn_low': 60255,
  'dl_high_mhz': 1675.0,
  'dl_low_mhz': 1670.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'TDD',
  'name': 'TD 1700',
  'note': None,
  'release': '18.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '65',
  'bandwidth_mhz': '90',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 66435,
  'dl_earfcn_low': 65536,
  'dl_high_mhz': 2200.0,
  'dl_low_mhz': 2110.0,
  'duplex_spacing_mhz': 190.0,
  'geographical_area': 'Global',
  'mode': 'FDD',
  'name': '2100+',
  'note': None,
  'release': '13.2',
  'ul_earfcn_high': 131971,
  'ul_earfcn_low': 131072,
  'ul_high_mhz': 2010.0,
  'ul_low_mhz': 1920.0},
 {'band': '66',
  'bandwidth_mhz': '90 / 70',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 67335,
  'dl_earfcn_low': 66436,
  'dl_high_mhz': 2200.0,
  'dl_low_mhz': 2110.0,
  'duplex_spacing_mhz': 400.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': 'AWS',
  'note': None,
  'release': '13.2',
  'ul_earfcn_high': 132671,
  'ul_earfcn_low': 131972,
  'ul_high_mhz': 1780.0,
  'ul_low_mhz': 1710.0},
 {'band': '67',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 67535,
  'dl_earfcn_low': 67336,
  'dl_high_mhz': 758.0,
  'dl_low_mhz': 738.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EMEA',
  'mode': 'SDL',
  'name': '700 EU',
  'note': 'CA',
  'release': '13.2',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '68',
  'bandwidth_mhz': '30',
  'channel_bandwidths_mhz': [5, 10, 15],
  'dl_earfcn_high': 67835,
  'dl_earfcn_low': 67536,
  'dl_high_mhz': 783.0,
  'dl_low_mhz': 753.0,
  'duplex_spacing_mhz': 55.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '700 ME',
  'note': None,
  'release': '13.3',
  'ul_earfcn_high': 132971,
  'ul_earfcn_low': 132672,
  'ul_high_mhz': 728.0,
  'ul_low_mhz': 698.0},
 {'band': '69',
  'bandwidth_mhz': '50',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 68335,
  'dl_earfcn_low': 67836,
  'dl_high_mhz': 2620.0,
  'dl_low_mhz': 2570.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'SDL',
  'name': 'DL b38',
  'note': 'CA',
  'release': '14.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '70',
  'bandwidth_mhz': '25 / 15',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 68585,
  'dl_earfcn_low': 68336,
  'dl_high_mhz': 2020.0,
  'dl_low_mhz': 1995.0,
  'duplex_spacing_mhz': 300.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': 'AWS-4',
  'note': None,
  'release': '14.0',
  'ul_earfcn_high': 133121,
  'ul_earfcn_low': 132972,
  'ul_high_mhz': 1710.0,
  'ul_low_mhz': 1695.0},
 {'band': '71',
  'bandwidth_mhz': '35',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 68935,
  'dl_earfcn_low': 68586,
  'dl_high_mhz': 652.0,
  'dl_low_mhz': 617.0,
  'duplex_spacing_mhz': -46.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '600',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': 133471,
  'ul_earfcn_low': 133122,
  'ul_high_mhz': 698.0,
  'ul_low_mhz': 663.0},
 {'band': '72',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 68985,
  'dl_earfcn_low': 68936,
  'dl_high_mhz': 466.0,
  'dl_low_mhz': 461.0,
  'duplex_spacing_mhz': 10.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '450 PMR/PAMR',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': 133521,
  'ul_earfcn_low': 133472,
  'ul_high_mhz': 456.0,
  'ul_low_mhz': 451.0},
 {'band': '73',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 69035,
  'dl_earfcn_low': 68986,
  'dl_high_mhz': 465.0,
  'dl_low_mhz': 460.0,
  'duplex_spacing_mhz': 10.0,
  'geographical_area': 'APAC',
  'mode': 'FDD',
  'name': '450 APAC',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': 133571,
  'ul_earfcn_low': 133522,
  'ul_high_mhz': 455.0,
  'ul_low_mhz': 450.0},
 {'band': '74',
  'bandwidth_mhz': '43',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 69465,
  'dl_earfcn_low': 69036,
  'dl_high_mhz': 1518.0,
  'dl_low_mhz': 1475.0,
  'duplex_spacing_mhz': 48.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': 'L-band',
  'note': None,
  'release': '15.0',
  'ul_earfcn_high': 134001,
  'ul_earfcn_low': 133572,
  'ul_high_mhz': 1470.0,
  'ul_low_mhz': 1427.0},
 {'band': '75',
  'bandwidth_mhz': '85',
  'channel_bandwidths_mhz': [5, 10, 15, 20],
  'dl_earfcn_high': 70315,
  'dl_earfcn_low': 69466,
  'dl_high_mhz': 1517.0,
  'dl_low_mhz': 1432.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EU',
  'mode': 'SDL',
  'name': 'DL b50',
  'note': 'CA',
  'release': '15.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '76',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [5],
  'dl_earfcn_high': 70365,
  'dl_earfcn_low': 70316,
  'dl_high_mhz': 1432.0,
  'dl_low_mhz': 1427.0,
  'duplex_spacing_mhz': None,
  'geographical_area': 'EU',
  'mode': 'SDL',
  'name': 'DL b51',
  'note': 'CA',
  'release': '15.0',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '85',
  'bandwidth_mhz': '18',
  'channel_bandwidths_mhz': [5, 10],
  'dl_earfcn_high': 70545,
  'dl_earfcn_low': 70366,
  'dl_high_mhz': 746.0,
  'dl_low_mhz': 728.0,
  'duplex_spacing_mhz': 30.0,
  'geographical_area': 'NAR',
  'mode': 'FDD',
  'name': '700 a+',
  'note': None,
  'release': '15.2',
  'ul_earfcn_high': 134181,
  'ul_earfcn_low': 134002,
  'ul_high_mhz': 716.0,
  'ul_low_mhz': 698.0},
 {'band': '87',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 70595,
  'dl_earfcn_low': 70546,
  'dl_high_mhz': 425.0,
  'dl_low_mhz': 420.0,
  'duplex_spacing_mhz': 10.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '410',
  'note': None,
  'release': '16.2',
  'ul_earfcn_high': 134231,
  'ul_earfcn_low': 134182,
  'ul_high_mhz': 415.0,
  'ul_low_mhz': 410.0},
 {'band': '88',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 70645,
  'dl_earfcn_low': 70596,
  'dl_high_mhz': 427.0,
  'dl_low_mhz': 422.0,
  'duplex_spacing_mhz': 10.0,
  'geographical_area': 'EMEA',
  'mode': 'FDD',
  'name': '410+',
  'note': None,
  'release': '16.2',
  'ul_earfcn_high': 134281,
  'ul_earfcn_low': 134232,
  'ul_high_mhz': 417.0,
  'ul_low_mhz': 412.0},
 {'band': '103',
  'bandwidth_mhz': '1',
  'channel_bandwidths_mhz': [],
  'dl_earfcn_high': 70655,
  'dl_earfcn_low': 70646,
  'dl_high_mhz': 758.0,
  'dl_low_mhz': 757.0,
  'duplex_spacing_mhz': -30.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NB-IoT',
  'note': 'NB-IoT',
  'release': '17.5',
  'ul_earfcn_high': 134291,
  'ul_earfcn_low': 134282,
  'ul_high_mhz': 788.0,
  'ul_low_mhz': 787.0},
 {'band': '106',
  'bandwidth_mhz': '5',
  'channel_bandwidths_mhz': [1.4, 3],
  'dl_earfcn_high': 70705,
  'dl_earfcn_low': 70656,
  'dl_high_mhz': 940.0,
  'dl_low_mhz': 935.0,
  'duplex_spacing_mhz': 39.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': '900',
  'note': None,
  'release': '18.2',
  'ul_earfcn_high': 134341,
  'ul_earfcn_low': 134292,
  'ul_high_mhz': 901.0,
  'ul_low_mhz': 896.0},
 {'band': '107',
  'bandwidth_mhz': '40',
  'channel_bandwidths_mhz': [1.4, 3],
  'dl_earfcn_high': 71055,
  'dl_earfcn_low': 70656,
  'dl_high_mhz': 652.0,
  'dl_low_mhz': 612.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'SDL',
  'name': 'DL 600',
  'note': 'Broadcast',
  'release': '18.3',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '108',
  'bandwidth_mhz': '228',
  'channel_bandwidths_mhz': [1.4, 3],
  'dl_earfcn_high': 73335,
  'dl_earfcn_low': 71056,
  'dl_high_mhz': 698.0,
  'dl_low_mhz': 470.0,
  'duplex_spacing_mhz': None,
  'geographical_area': None,
  'mode': 'SDL',
  'name': 'DL 500',
  'note': 'Broadcast',
  'release': '18.3',
  'ul_earfcn_high': None,
  'ul_earfcn_low': None,
  'ul_high_mhz': None,
  'ul_low_mhz': None},
 {'band': '111',
  'bandwidth_mhz': '10',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10],
  'dl_earfcn_high': 73485,
  'dl_earfcn_low': 73386,
  'dl_high_mhz': 1830.0,
  'dl_low_mhz': 1820.0,
  'duplex_spacing_mhz': 20.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'HD-1800',
  'note': None,
  'release': '19.0',
  'ul_earfcn_high': 134441,
  'ul_earfcn_low': 134342,
  'ul_high_mhz': 1810.0,
  'ul_low_mhz': 1800.0},
 {'band': '256',
  'bandwidth_mhz': '30',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 229375,
  'dl_earfcn_low': 229076,
  'dl_high_mhz': 2200.0,
  'dl_low_mhz': 2170.0,
  'duplex_spacing_mhz': 190.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NTN 2000+',
  'note': 'NTN',
  'release': '18.0',
  'ul_earfcn_high': 262143,
  'ul_earfcn_low': 261844,
  'ul_high_mhz': 2010.0,
  'ul_low_mhz': 1980.0},
 {'band': '255',
  'bandwidth_mhz': '34',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 229075,
  'dl_earfcn_low': 228736,
  'dl_high_mhz': 1559.0,
  'dl_low_mhz': 1525.0,
  'duplex_spacing_mhz': -101.5,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NTN 1600+',
  'note': 'NTN',
  'release': '18.0',
  'ul_earfcn_high': 261843,
  'ul_earfcn_low': 261504,
  'ul_high_mhz': 1660.5,
  'ul_low_mhz': 1626.5},
 {'band': '254',
  'bandwidth_mhz': '16.5',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15],
  'dl_earfcn_high': 228735,
  'dl_earfcn_low': 228571,
  'dl_high_mhz': 2500.0,
  'dl_low_mhz': 2483.5,
  'duplex_spacing_mhz': 873.5,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NTN 2500',
  'note': 'NTN',
  'release': '18.0',
  'ul_earfcn_high': 261503,
  'ul_earfcn_low': 261339,
  'ul_high_mhz': 1626.5,
  'ul_low_mhz': 1610.0},
 {'band': '253',
  'bandwidth_mhz': '7',
  'channel_bandwidths_mhz': [1.4, 3, 5],
  'dl_earfcn_high': 228570,
  'dl_earfcn_low': 228501,
  'dl_high_mhz': 1525.0,
  'dl_low_mhz': 1518.0,
  'duplex_spacing_mhz': -150.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NTN 1600',
  'note': 'NTN',
  'release': '18.0',
  'ul_earfcn_high': 261338,
  'ul_earfcn_low': 261269,
  'ul_high_mhz': 1675.0,
  'ul_low_mhz': 1668.0},
 {'band': '252',
  'bandwidth_mhz': '20',
  'channel_bandwidths_mhz': [1.4, 3, 5, 10, 15, 20],
  'dl_earfcn_high': 228500,
  'dl_earfcn_low': 228301,
  'dl_high_mhz': 2200.0,
  'dl_low_mhz': 2180.0,
  'duplex_spacing_mhz': 180.0,
  'geographical_area': None,
  'mode': 'FDD',
  'name': 'NTN 2000',
  'note': 'NTN',
  'release': '19.0',
  'ul_earfcn_high': 261268,
  'ul_earfcn_low': 261069,
  'ul_high_mhz': 2020.0,
  'ul_low_mhz': 2000.0}]


def _nearest_integer(value: float) -> int:
    """Membulatkan ke kanal LTE terdekat. 1 EARFCN = 0.1 MHz."""

    return floor(value + 0.5)


def _round_or_none(value: float | None) -> float | None:
    if value is None:
        return None

    return round(value, 6)


def _calculate_earfcn(
    *,
    frequency_mhz: float,
    low_frequency_mhz: float | None,
    low_earfcn: int | None,
) -> int | None:
    if low_frequency_mhz is None or low_earfcn is None:
        return None

    return int(
        low_earfcn
        + _nearest_integer(
            (frequency_mhz - low_frequency_mhz)
            / LTE_CHANNEL_SPACING_MHZ
        )
    )


def _calculate_channel_frequency(
    *,
    earfcn: int | None,
    low_frequency_mhz: float | None,
    low_earfcn: int | None,
) -> float | None:
    if earfcn is None or low_frequency_mhz is None or low_earfcn is None:
        return None

    return low_frequency_mhz + (
        (earfcn - low_earfcn) * LTE_CHANNEL_SPACING_MHZ
    )


def _is_in_range(
    frequency_mhz: float,
    low_mhz: float | None,
    high_mhz: float | None,
) -> bool:
    if low_mhz is None or high_mhz is None:
        return False

    return low_mhz <= frequency_mhz <= high_mhz


def _build_result(
    *,
    raw_frequency_mhz: float,
    band: dict[str, Any],
    direction: str,
) -> dict[str, Any]:
    mode = band["mode"]
    is_uplink = direction == "UL"
    is_tdd = direction == "TDD"

    if is_uplink:
        earfcn_ul = _calculate_earfcn(
            frequency_mhz=raw_frequency_mhz,
            low_frequency_mhz=band["ul_low_mhz"],
            low_earfcn=band["ul_earfcn_low"],
        )
        channel_ul_mhz = _calculate_channel_frequency(
            earfcn=earfcn_ul,
            low_frequency_mhz=band["ul_low_mhz"],
            low_earfcn=band["ul_earfcn_low"],
        )

        dl_to_ul_offset_mhz = (
            band["ul_low_mhz"] - band["dl_low_mhz"]
            if band["ul_low_mhz"] is not None
            else None
        )

        channel_dl_mhz = (
            channel_ul_mhz - dl_to_ul_offset_mhz
            if channel_ul_mhz is not None
            and dl_to_ul_offset_mhz is not None
            else None
        )

        earfcn_dl = _calculate_earfcn(
            frequency_mhz=channel_dl_mhz,
            low_frequency_mhz=band["dl_low_mhz"],
            low_earfcn=band["dl_earfcn_low"],
        )

        selected_earfcn = earfcn_ul
        selected_channel_frequency_mhz = channel_ul_mhz
        direction_label = "Uplink"
        classification_note = "Frequency-based LTE FDD uplink candidate"

    else:
        earfcn_dl = _calculate_earfcn(
            frequency_mhz=raw_frequency_mhz,
            low_frequency_mhz=band["dl_low_mhz"],
            low_earfcn=band["dl_earfcn_low"],
        )
        channel_dl_mhz = _calculate_channel_frequency(
            earfcn=earfcn_dl,
            low_frequency_mhz=band["dl_low_mhz"],
            low_earfcn=band["dl_earfcn_low"],
        )

        if is_tdd:
            channel_ul_mhz = channel_dl_mhz
            earfcn_ul = None
            direction_label = "TDD shared DL/UL"
            classification_note = "Frequency-based LTE TDD candidate"
        else:
            dl_to_ul_offset_mhz = (
                band["ul_low_mhz"] - band["dl_low_mhz"]
                if band["ul_low_mhz"] is not None
                else None
            )

            channel_ul_mhz = (
                channel_dl_mhz + dl_to_ul_offset_mhz
                if channel_dl_mhz is not None
                and dl_to_ul_offset_mhz is not None
                else None
            )

            earfcn_ul = _calculate_earfcn(
                frequency_mhz=channel_ul_mhz,
                low_frequency_mhz=band["ul_low_mhz"],
                low_earfcn=band["ul_earfcn_low"],
            )

            direction_label = (
                "Downlink only" if mode == "SDL" else "Downlink"
            )
            classification_note = (
                "Frequency-based LTE SDL downlink candidate"
                if mode == "SDL"
                else "Frequency-based LTE FDD downlink candidate"
            )

        selected_earfcn = earfcn_dl
        selected_channel_frequency_mhz = channel_dl_mhz

    channel_offset_khz = None

    if selected_channel_frequency_mhz is not None:
        channel_offset_khz = round(
            (raw_frequency_mhz - selected_channel_frequency_mhz) * 1000,
            3,
        )

    return {
        "mode": "4G LTE",
        "technology": "LTE",
        "generation": "4G",
        "band": band["name"],
        "band_number": band["band"],
        "band_code": f"B{band['band']}",
        "standard_band": f"LTE Band {band['band']}",
        "name": band["name"],
        "duplex_mode": mode,
        "direction": direction,
        "direction_label": direction_label,
        "detected_frequency_mhz": round(raw_frequency_mhz, 6),
        "freq_dl_mhz": _round_or_none(channel_dl_mhz),
        "freq_ul_mhz": _round_or_none(channel_ul_mhz),
        "earfcn": selected_earfcn,
        "earfcn_dl": earfcn_dl,
        "earfcn_ul": earfcn_ul,
        "fcn": selected_earfcn,
        "fcn_ul": earfcn_ul,
        "dl_low_mhz": band["dl_low_mhz"],
        "dl_high_mhz": band["dl_high_mhz"],
        "ul_low_mhz": band["ul_low_mhz"],
        "ul_high_mhz": band["ul_high_mhz"],
        "duplex_spacing_mhz": band["duplex_spacing_mhz"],
        "channel_spacing_mhz": LTE_CHANNEL_SPACING_MHZ,
        "channel_offset_khz": channel_offset_khz,
        "channel_bandwidths_mhz": band["channel_bandwidths_mhz"],
        "bandwidth_mhz": band["bandwidth_mhz"],
        "geographical_area": band["geographical_area"],
        "release": band["release"],
        "note": band["note"],
        "classification_note": classification_note,
    }


def classify_lte(
    frequency_mhz: float,
) -> list[dict[str, Any]]:
    """
    Mencocokkan satu peak frekuensi dengan band LTE/E-UTRA.

    Fungsi mengembalikan list karena satu frekuensi dapat overlap
    dengan beberapa LTE band, bahkan bisa menjadi DL pada satu band
    dan UL pada band lain.
    """

    try:
        frequency = float(frequency_mhz)
    except (TypeError, ValueError):
        return []

    if frequency <= 0:
        return []

    matches: list[dict[str, Any]] = []

    for band in LTE_BANDS:
        mode = band["mode"]

        if mode == "TDD":
            if _is_in_range(
                frequency,
                band["dl_low_mhz"],
                band["dl_high_mhz"],
            ):
                matches.append(
                    _build_result(
                        raw_frequency_mhz=frequency,
                        band=band,
                        direction="TDD",
                    )
                )

            continue

        if _is_in_range(
            frequency,
            band["dl_low_mhz"],
            band["dl_high_mhz"],
        ):
            matches.append(
                _build_result(
                    raw_frequency_mhz=frequency,
                    band=band,
                    direction="DL",
                )
            )

        if mode == "FDD" and _is_in_range(
            frequency,
            band["ul_low_mhz"],
            band["ul_high_mhz"],
        ):
            matches.append(
                _build_result(
                    raw_frequency_mhz=frequency,
                    band=band,
                    direction="UL",
                )
            )

    return matches
