"""5G NR FR1 frequency-band classifier.

Data source:
- Squimway NR frequency bands for FR1 38.104 (Rel 19 Dec 2025)

This classifier is frequency-based. It only returns possible 5G NR band
candidates from the detected peak frequency. It does not decode 5G NR signals.
"""

from __future__ import annotations

from typing import Any


NR_FR1_BANDS: list[dict[str, Any]] = [
    {
        "band": "n1",
        "name": "2100",
        "mode": "FDD",
        "dl_low_mhz": 2110.0,
        "dl_mid_mhz": 2140.0,
        "dl_high_mhz": 2170.0,
        "dl_low_arfcn": 422000,
        "dl_mid_arfcn": 428000,
        "dl_high_arfcn": 434000,
        "ul_low_mhz": 1920.0,
        "ul_mid_mhz": 1950.0,
        "ul_high_mhz": 1980.0,
        "ul_low_arfcn": 384000,
        "ul_mid_arfcn": 390000,
        "ul_high_arfcn": 396000,
        "duplex_spacing_mhz": 190.0,
        "equivalent_lte_band": "1",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n2",
        "name": "1900 PCS",
        "mode": "FDD",
        "dl_low_mhz": 1930.0,
        "dl_mid_mhz": 1960.0,
        "dl_high_mhz": 1990.0,
        "dl_low_arfcn": 386000,
        "dl_mid_arfcn": 392000,
        "dl_high_arfcn": 398000,
        "ul_low_mhz": 1850.0,
        "ul_mid_mhz": 1880.0,
        "ul_high_mhz": 1910.0,
        "ul_low_arfcn": 370000,
        "ul_mid_arfcn": 376000,
        "ul_high_arfcn": 382000,
        "duplex_spacing_mhz": 80.0,
        "equivalent_lte_band": "2",
        "area": "NAR",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n3",
        "name": "1800",
        "mode": "FDD",
        "dl_low_mhz": 1805.0,
        "dl_mid_mhz": 1842.5,
        "dl_high_mhz": 1880.0,
        "dl_low_arfcn": 361000,
        "dl_mid_arfcn": 368500,
        "dl_high_arfcn": 376000,
        "ul_low_mhz": 1710.0,
        "ul_mid_mhz": 1747.5,
        "ul_high_mhz": 1785.0,
        "ul_low_arfcn": 342000,
        "ul_mid_arfcn": 349500,
        "ul_high_arfcn": 357000,
        "duplex_spacing_mhz": 95.0,
        "equivalent_lte_band": "3",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n5",
        "name": "850",
        "mode": "FDD",
        "dl_low_mhz": 869.0,
        "dl_mid_mhz": 881.5,
        "dl_high_mhz": 894.0,
        "dl_low_arfcn": 173800,
        "dl_mid_arfcn": 176300,
        "dl_high_arfcn": 178800,
        "ul_low_mhz": 824.0,
        "ul_mid_mhz": 836.5,
        "ul_high_mhz": 849.0,
        "ul_low_arfcn": 164800,
        "ul_mid_arfcn": 167300,
        "ul_high_arfcn": 169800,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": "5",
        "area": "Global",
        "release": "15.0",
        "note": "1"
    },
    {
        "band": "n7",
        "name": "2600",
        "mode": "FDD",
        "dl_low_mhz": 2620.0,
        "dl_mid_mhz": 2655.0,
        "dl_high_mhz": 2690.0,
        "dl_low_arfcn": 524000,
        "dl_mid_arfcn": 531000,
        "dl_high_arfcn": 538000,
        "ul_low_mhz": 2500.0,
        "ul_mid_mhz": 2535.0,
        "ul_high_mhz": 2570.0,
        "ul_low_arfcn": 500000,
        "ul_mid_arfcn": 507000,
        "ul_high_arfcn": 514000,
        "duplex_spacing_mhz": 120.0,
        "equivalent_lte_band": "7",
        "area": "EMEA",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n8",
        "name": "900 GSM",
        "mode": "FDD",
        "dl_low_mhz": 925.0,
        "dl_mid_mhz": 942.5,
        "dl_high_mhz": 960.0,
        "dl_low_arfcn": 185000,
        "dl_mid_arfcn": 188500,
        "dl_high_arfcn": 192000,
        "ul_low_mhz": 880.0,
        "ul_mid_mhz": 897.5,
        "ul_high_mhz": 915.0,
        "ul_low_arfcn": 176000,
        "ul_mid_arfcn": 179500,
        "ul_high_arfcn": 183000,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": "8",
        "area": "Global",
        "release": "15.0",
        "note": "3"
    },
    {
        "band": "n12",
        "name": "700 a",
        "mode": "FDD",
        "dl_low_mhz": 729.0,
        "dl_mid_mhz": 737.5,
        "dl_high_mhz": 746.0,
        "dl_low_arfcn": 145800,
        "dl_mid_arfcn": 147500,
        "dl_high_arfcn": 149200,
        "ul_low_mhz": 699.0,
        "ul_mid_mhz": 707.5,
        "ul_high_mhz": 716.0,
        "ul_low_arfcn": 139800,
        "ul_mid_arfcn": 141500,
        "ul_high_arfcn": 143200,
        "duplex_spacing_mhz": 30.0,
        "equivalent_lte_band": "12",
        "area": "NAR",
        "release": "15.2",
        "note": None
    },
    {
        "band": "n13",
        "name": "700 c",
        "mode": "FDD",
        "dl_low_mhz": 746.0,
        "dl_mid_mhz": 751.0,
        "dl_high_mhz": 756.0,
        "dl_low_arfcn": 149200,
        "dl_mid_arfcn": 150200,
        "dl_high_arfcn": 151200,
        "ul_low_mhz": 777.0,
        "ul_mid_mhz": 782.0,
        "ul_high_mhz": 787.0,
        "ul_low_arfcn": 155400,
        "ul_mid_arfcn": 156400,
        "ul_high_arfcn": 157400,
        "duplex_spacing_mhz": -31.0,
        "equivalent_lte_band": "13",
        "area": "NAR",
        "release": "17.0",
        "note": None
    },
    {
        "band": "n14",
        "name": "700 PS",
        "mode": "FDD",
        "dl_low_mhz": 758.0,
        "dl_mid_mhz": 763.0,
        "dl_high_mhz": 768.0,
        "dl_low_arfcn": 151600,
        "dl_mid_arfcn": 152600,
        "dl_high_arfcn": 153600,
        "ul_low_mhz": 788.0,
        "ul_mid_mhz": 793.0,
        "ul_high_mhz": 798.0,
        "ul_low_arfcn": 157600,
        "ul_mid_arfcn": 158600,
        "ul_high_arfcn": 159600,
        "duplex_spacing_mhz": -30.0,
        "equivalent_lte_band": "14",
        "area": "NAR",
        "release": "16.0",
        "note": None
    },
    {
        "band": "n18",
        "name": "800 Lower",
        "mode": "FDD",
        "dl_low_mhz": 860.0,
        "dl_mid_mhz": 867.5,
        "dl_high_mhz": 875.0,
        "dl_low_arfcn": 172000,
        "dl_mid_arfcn": 173500,
        "dl_high_arfcn": 175000,
        "ul_low_mhz": 815.0,
        "ul_mid_mhz": 822.5,
        "ul_high_mhz": 830.0,
        "ul_low_arfcn": 163000,
        "ul_mid_arfcn": 164500,
        "ul_high_arfcn": 166000,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": "18",
        "area": "Japan",
        "release": "16.0",
        "note": None
    },
    {
        "band": "n20",
        "name": "800",
        "mode": "FDD",
        "dl_low_mhz": 791.0,
        "dl_mid_mhz": 806.0,
        "dl_high_mhz": 821.0,
        "dl_low_arfcn": 158200,
        "dl_mid_arfcn": 161200,
        "dl_high_arfcn": 164200,
        "ul_low_mhz": 832.0,
        "ul_mid_mhz": 847.0,
        "ul_high_mhz": 862.0,
        "ul_low_arfcn": 166400,
        "ul_mid_arfcn": 169400,
        "ul_high_arfcn": 172400,
        "duplex_spacing_mhz": -41.0,
        "equivalent_lte_band": "20",
        "area": "EMEA",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n24",
        "name": "1600 L",
        "mode": "FDD",
        "dl_low_mhz": 1525.0,
        "dl_mid_mhz": 1542.0,
        "dl_high_mhz": 1559.0,
        "dl_low_arfcn": 305000,
        "dl_mid_arfcn": 308400,
        "dl_high_arfcn": 311800,
        "ul_low_mhz": 1626.5,
        "ul_mid_mhz": 1643.5,
        "ul_high_mhz": 1660.5,
        "ul_low_arfcn": 325300,
        "ul_mid_arfcn": 328700,
        "ul_high_arfcn": 332100,
        "duplex_spacing_mhz": -101.5,
        "equivalent_lte_band": "24",
        "area": "NAR",
        "release": "17.1",
        "note": None
    },
    {
        "band": "n25",
        "name": "1900+",
        "mode": "FDD",
        "dl_low_mhz": 1930.0,
        "dl_mid_mhz": 1962.5,
        "dl_high_mhz": 1995.0,
        "dl_low_arfcn": 386000,
        "dl_mid_arfcn": 392500,
        "dl_high_arfcn": 399000,
        "ul_low_mhz": 1850.0,
        "ul_mid_mhz": 1882.5,
        "ul_high_mhz": 1915.0,
        "ul_low_arfcn": 370000,
        "ul_mid_arfcn": 376500,
        "ul_high_arfcn": 383000,
        "duplex_spacing_mhz": 80.0,
        "equivalent_lte_band": "25",
        "area": "NAR",
        "release": "15.2",
        "note": "5"
    },
    {
        "band": "n26",
        "name": "850+",
        "mode": "FDD",
        "dl_low_mhz": 859.0,
        "dl_mid_mhz": 876.5,
        "dl_high_mhz": 894.0,
        "dl_low_arfcn": 171800,
        "dl_mid_arfcn": 175300,
        "dl_high_arfcn": 178800,
        "ul_low_mhz": 814.0,
        "ul_mid_mhz": 831.5,
        "ul_high_mhz": 849.0,
        "ul_low_arfcn": 162800,
        "ul_mid_arfcn": 166300,
        "ul_high_arfcn": 169800,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": "26",
        "area": "NAR",
        "release": "16.3",
        "note": "2"
    },
    {
        "band": "n28",
        "name": "700 APT",
        "mode": "FDD",
        "dl_low_mhz": 758.0,
        "dl_mid_mhz": 780.5,
        "dl_high_mhz": 803.0,
        "dl_low_arfcn": 151600,
        "dl_mid_arfcn": 156100,
        "dl_high_arfcn": 160600,
        "ul_low_mhz": 703.0,
        "ul_mid_mhz": 725.5,
        "ul_high_mhz": 748.0,
        "ul_low_arfcn": 140600,
        "ul_mid_arfcn": 145100,
        "ul_high_arfcn": 149600,
        "duplex_spacing_mhz": 55.0,
        "equivalent_lte_band": "28",
        "area": "APAC,EU",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n29",
        "name": "700 d",
        "mode": "SDL",
        "dl_low_mhz": 717.0,
        "dl_mid_mhz": 722.5,
        "dl_high_mhz": 728.0,
        "dl_low_arfcn": 143400,
        "dl_mid_arfcn": 144500,
        "dl_high_arfcn": 145600,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "29",
        "area": "NAR",
        "release": "16.1",
        "note": None
    },
    {
        "band": "n30",
        "name": "2300 WCS",
        "mode": "FDD",
        "dl_low_mhz": 2350.0,
        "dl_mid_mhz": 2355.0,
        "dl_high_mhz": 2360.0,
        "dl_low_arfcn": 470000,
        "dl_mid_arfcn": 471000,
        "dl_high_arfcn": 472000,
        "ul_low_mhz": 2305.0,
        "ul_mid_mhz": 2310.0,
        "ul_high_mhz": 2315.0,
        "ul_low_arfcn": 461000,
        "ul_mid_arfcn": 462000,
        "ul_high_arfcn": 463000,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": "30",
        "area": "NAR",
        "release": "16.0",
        "note": None
    },
    {
        "band": "n31",
        "name": "450",
        "mode": "FDD",
        "dl_low_mhz": 462.5,
        "dl_mid_mhz": 465.0,
        "dl_high_mhz": 467.5,
        "dl_low_arfcn": 92500,
        "dl_mid_arfcn": 93000,
        "dl_high_arfcn": 93500,
        "ul_low_mhz": 452.5,
        "ul_mid_mhz": 455.0,
        "ul_high_mhz": 457.5,
        "ul_low_arfcn": 90500,
        "ul_mid_arfcn": 91000,
        "ul_high_arfcn": 91500,
        "duplex_spacing_mhz": 10.0,
        "equivalent_lte_band": "31",
        "area": "Global",
        "release": "18.4",
        "note": None
    },
    {
        "band": "n34",
        "name": "TD 2000",
        "mode": "TDD",
        "dl_low_mhz": 2010.0,
        "dl_mid_mhz": 2017.5,
        "dl_high_mhz": 2025.0,
        "dl_low_arfcn": 402000,
        "dl_mid_arfcn": 403500,
        "dl_high_arfcn": 405000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "34",
        "area": "EMEA",
        "release": "15.2",
        "note": None
    },
    {
        "band": "n38",
        "name": "TD 2600",
        "mode": "TDD",
        "dl_low_mhz": 2570.0,
        "dl_mid_mhz": 2595.0,
        "dl_high_mhz": 2620.0,
        "dl_low_arfcn": 514000,
        "dl_mid_arfcn": 519000,
        "dl_high_arfcn": 524000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "38",
        "area": "EMEA",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n39",
        "name": "TD 1900+",
        "mode": "TDD",
        "dl_low_mhz": 1880.0,
        "dl_mid_mhz": 1900.0,
        "dl_high_mhz": 1920.0,
        "dl_low_arfcn": 376000,
        "dl_mid_arfcn": 380000,
        "dl_high_arfcn": 384000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "39",
        "area": "China",
        "release": "15.2",
        "note": None
    },
    {
        "band": "n40",
        "name": "TD 2300",
        "mode": "TDD",
        "dl_low_mhz": 2300.0,
        "dl_mid_mhz": 2350.0,
        "dl_high_mhz": 2400.0,
        "dl_low_arfcn": 460000,
        "dl_mid_arfcn": 470000,
        "dl_high_arfcn": 480000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "40",
        "area": "APAC",
        "release": "15.2",
        "note": None
    },
    {
        "band": "n41",
        "name": "TD 2600+",
        "mode": "TDD",
        "dl_low_mhz": 2496.0,
        "dl_mid_mhz": 2593.0,
        "dl_high_mhz": 2690.0,
        "dl_low_arfcn": 499200,
        "dl_mid_arfcn": 518601,
        "dl_high_arfcn": 537999,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "41",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n46",
        "name": "TD Unlicensed",
        "mode": "TDD",
        "dl_low_mhz": 5150.0,
        "dl_mid_mhz": 5537.5,
        "dl_high_mhz": 5925.0,
        "dl_low_arfcn": 743334,
        "dl_mid_arfcn": 769167,
        "dl_high_arfcn": 795000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "46",
        "area": "Global",
        "release": "16.5",
        "note": None
    },
    {
        "band": "n47",
        "name": "TD V2X",
        "mode": "TDD",
        "dl_low_mhz": 5855.0,
        "dl_mid_mhz": 5890.0,
        "dl_high_mhz": 5925.0,
        "dl_low_arfcn": 790334,
        "dl_mid_arfcn": 792667,
        "dl_high_arfcn": 795000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "47",
        "area": "Global",
        "release": "15.7",
        "note": None
    },
    {
        "band": "n48",
        "name": "TD 3600",
        "mode": "TDD",
        "dl_low_mhz": 3550.0,
        "dl_mid_mhz": 3625.0,
        "dl_high_mhz": 3700.0,
        "dl_low_arfcn": 636667,
        "dl_mid_arfcn": 641667,
        "dl_high_arfcn": 646666,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "48",
        "area": "Global",
        "release": "16.0",
        "note": "2"
    },
    {
        "band": "n50",
        "name": "TD 1500+",
        "mode": "TDD",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1474.5,
        "dl_high_mhz": 1517.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 294900,
        "dl_high_arfcn": 303400,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "50",
        "area": "EU",
        "release": "15.3",
        "note": "7"
    },
    {
        "band": "n51",
        "name": "TD 1500-",
        "mode": "TDD",
        "dl_low_mhz": 1427.0,
        "dl_mid_mhz": 1429.5,
        "dl_high_mhz": 1432.0,
        "dl_low_arfcn": 285400,
        "dl_mid_arfcn": 285900,
        "dl_high_arfcn": 286400,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "51",
        "area": "EU",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n53",
        "name": "TD 2500",
        "mode": "TDD",
        "dl_low_mhz": 2483.5,
        "dl_mid_mhz": 2489.3,
        "dl_high_mhz": 2495.0,
        "dl_low_arfcn": 496700,
        "dl_mid_arfcn": 497860,
        "dl_high_arfcn": 499000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "53",
        "area": None,
        "release": "16.3",
        "note": None
    },
    {
        "band": "n54",
        "name": "TD 1700",
        "mode": "TDD",
        "dl_low_mhz": 1670.0,
        "dl_mid_mhz": 1672.5,
        "dl_high_mhz": 1675.0,
        "dl_low_arfcn": 334000,
        "dl_mid_arfcn": 334500,
        "dl_high_arfcn": 335000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "54",
        "area": None,
        "release": "18.1",
        "note": None
    },
    {
        "band": "n65",
        "name": "2100+",
        "mode": "FDD",
        "dl_low_mhz": 2110.0,
        "dl_mid_mhz": 2155.0,
        "dl_high_mhz": 2200.0,
        "dl_low_arfcn": 422000,
        "dl_mid_arfcn": 431000,
        "dl_high_arfcn": 440000,
        "ul_low_mhz": 1920.0,
        "ul_mid_mhz": 1965.0,
        "ul_high_mhz": 2010.0,
        "ul_low_arfcn": 384000,
        "ul_mid_arfcn": 393000,
        "ul_high_arfcn": 402000,
        "duplex_spacing_mhz": 190.0,
        "equivalent_lte_band": "65",
        "area": "Global",
        "release": "16.0",
        "note": None
    },
    {
        "band": "n66",
        "name": "AWS",
        "mode": "FDD",
        "dl_low_mhz": 2110.0,
        "dl_mid_mhz": 2155.0,
        "dl_high_mhz": 2200.0,
        "dl_low_arfcn": 422000,
        "dl_mid_arfcn": 431000,
        "dl_high_arfcn": 440000,
        "ul_low_mhz": 1710.0,
        "ul_mid_mhz": 1745.0,
        "ul_high_mhz": 1780.0,
        "ul_low_arfcn": 342000,
        "ul_mid_arfcn": 349000,
        "ul_high_arfcn": 356000,
        "duplex_spacing_mhz": 400.0,
        "equivalent_lte_band": "66",
        "area": "NAR",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n67",
        "name": "700 EU",
        "mode": "SDL",
        "dl_low_mhz": 738.0,
        "dl_mid_mhz": 748.0,
        "dl_high_mhz": 758.0,
        "dl_low_arfcn": 147600,
        "dl_mid_arfcn": 149600,
        "dl_high_arfcn": 151600,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "67",
        "area": "EMEA",
        "release": "17.2",
        "note": None
    },
    {
        "band": "n68",
        "name": "700 ME",
        "mode": "FDD",
        "dl_low_mhz": 753.0,
        "dl_mid_mhz": 768.0,
        "dl_high_mhz": 783.0,
        "dl_low_arfcn": 150600,
        "dl_mid_arfcn": 153600,
        "dl_high_arfcn": 156600,
        "ul_low_mhz": 698.0,
        "ul_mid_mhz": 713.0,
        "ul_high_mhz": 728.0,
        "ul_low_arfcn": 139600,
        "ul_mid_arfcn": 142600,
        "ul_high_arfcn": 145600,
        "duplex_spacing_mhz": 55.0,
        "equivalent_lte_band": "68",
        "area": "EMEA",
        "release": "19.1",
        "note": None
    },
    {
        "band": "n70",
        "name": "AWS-4",
        "mode": "FDD",
        "dl_low_mhz": 1995.0,
        "dl_mid_mhz": 2007.5,
        "dl_high_mhz": 2020.0,
        "dl_low_arfcn": 399000,
        "dl_mid_arfcn": 401500,
        "dl_high_arfcn": 404000,
        "ul_low_mhz": 1695.0,
        "ul_mid_mhz": 1702.5,
        "ul_high_mhz": 1710.0,
        "ul_low_arfcn": 339000,
        "ul_mid_arfcn": 340500,
        "ul_high_arfcn": 342000,
        "duplex_spacing_mhz": 300.0,
        "equivalent_lte_band": "70",
        "area": "NAR",
        "release": "15.0",
        "note": "4"
    },
    {
        "band": "n71",
        "name": "600",
        "mode": "FDD",
        "dl_low_mhz": 617.0,
        "dl_mid_mhz": 634.5,
        "dl_high_mhz": 652.0,
        "dl_low_arfcn": 123400,
        "dl_mid_arfcn": 126900,
        "dl_high_arfcn": 130400,
        "ul_low_mhz": 663.0,
        "ul_mid_mhz": 680.5,
        "ul_high_mhz": 698.0,
        "ul_low_arfcn": 132600,
        "ul_mid_arfcn": 136100,
        "ul_high_arfcn": 139600,
        "duplex_spacing_mhz": -46.0,
        "equivalent_lte_band": "71",
        "area": "NAR",
        "release": "15.0",
        "note": "12"
    },
    {
        "band": "n72",
        "name": "450 PMR/PAMR",
        "mode": "FDD",
        "dl_low_mhz": 461.0,
        "dl_mid_mhz": 463.5,
        "dl_high_mhz": 466.0,
        "dl_low_arfcn": 92200,
        "dl_mid_arfcn": 92700,
        "dl_high_arfcn": 93200,
        "ul_low_mhz": 451.0,
        "ul_mid_mhz": 453.5,
        "ul_high_mhz": 456.0,
        "ul_low_arfcn": 90200,
        "ul_mid_arfcn": 90700,
        "ul_high_arfcn": 91200,
        "duplex_spacing_mhz": 10.0,
        "equivalent_lte_band": "72",
        "area": "EMEA",
        "release": "18.4",
        "note": None
    },
    {
        "band": "n74",
        "name": "L-band",
        "mode": "FDD",
        "dl_low_mhz": 1475.0,
        "dl_mid_mhz": 1496.5,
        "dl_high_mhz": 1518.0,
        "dl_low_arfcn": 295000,
        "dl_mid_arfcn": 299300,
        "dl_high_arfcn": 303600,
        "ul_low_mhz": 1427.0,
        "ul_mid_mhz": 1448.5,
        "ul_high_mhz": 1470.0,
        "ul_low_arfcn": 285400,
        "ul_mid_arfcn": 289700,
        "ul_high_arfcn": 294000,
        "duplex_spacing_mhz": 48.0,
        "equivalent_lte_band": "74",
        "area": "EMEA",
        "release": "15.3",
        "note": None
    },
    {
        "band": "n75",
        "name": "DL 1500+",
        "mode": "SDL",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1474.5,
        "dl_high_mhz": 1517.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 294900,
        "dl_high_arfcn": 303400,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "75",
        "area": "EU",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n76",
        "name": "DL 1500-",
        "mode": "SDL",
        "dl_low_mhz": 1427.0,
        "dl_mid_mhz": 1429.5,
        "dl_high_mhz": 1432.0,
        "dl_low_arfcn": 285400,
        "dl_mid_arfcn": 285900,
        "dl_high_arfcn": 286400,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "76",
        "area": "EU",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n77",
        "name": "TD 3700",
        "mode": "TDD",
        "dl_low_mhz": 3300.0,
        "dl_mid_mhz": 3750.0,
        "dl_high_mhz": 4200.0,
        "dl_low_arfcn": 620000,
        "dl_mid_arfcn": 650000,
        "dl_high_arfcn": 680000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": None,
        "release": "15.0",
        "note": "C-Band"
    },
    {
        "band": "n78",
        "name": "TD 3500",
        "mode": "TDD",
        "dl_low_mhz": 3300.0,
        "dl_mid_mhz": 3550.0,
        "dl_high_mhz": 3800.0,
        "dl_low_arfcn": 620000,
        "dl_mid_arfcn": 636667,
        "dl_high_arfcn": 653333,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": None,
        "release": "15.0",
        "note": None
    },
    {
        "band": "n79",
        "name": "TD 4700",
        "mode": "TDD",
        "dl_low_mhz": 4400.0,
        "dl_mid_mhz": 4700.0,
        "dl_high_mhz": 5000.0,
        "dl_low_arfcn": 693334,
        "dl_mid_arfcn": 713334,
        "dl_high_arfcn": 733333,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": None,
        "release": "15.0",
        "note": None
    },
    {
        "band": "n80",
        "name": "UL n3",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 1710.0,
        "ul_mid_mhz": 1747.5,
        "ul_high_mhz": 1785.0,
        "ul_low_arfcn": 342000,
        "ul_mid_arfcn": 349500,
        "ul_high_arfcn": 357000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "3",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n81",
        "name": "UL n8",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 880.0,
        "ul_mid_mhz": 897.5,
        "ul_high_mhz": 915.0,
        "ul_low_arfcn": 176000,
        "ul_mid_arfcn": 179500,
        "ul_high_arfcn": 183000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "8",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n82",
        "name": "UL n20",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 832.0,
        "ul_mid_mhz": 847.0,
        "ul_high_mhz": 862.0,
        "ul_low_arfcn": 166400,
        "ul_mid_arfcn": 169400,
        "ul_high_arfcn": 172400,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "20",
        "area": "EMEA",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n83",
        "name": "UL n28",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 703.0,
        "ul_mid_mhz": 725.5,
        "ul_high_mhz": 748.0,
        "ul_low_arfcn": 140600,
        "ul_mid_arfcn": 145100,
        "ul_high_arfcn": 149600,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "28",
        "area": "APAC,EU",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n84",
        "name": "UL n1",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 1920.0,
        "ul_mid_mhz": 1950.0,
        "ul_high_mhz": 1980.0,
        "ul_low_arfcn": 384000,
        "ul_mid_arfcn": 390000,
        "ul_high_arfcn": 396000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "1",
        "area": "Global",
        "release": "15.0",
        "note": None
    },
    {
        "band": "n85",
        "name": "700 a+",
        "mode": "FDD",
        "dl_low_mhz": 728.0,
        "dl_mid_mhz": 737.0,
        "dl_high_mhz": 746.0,
        "dl_low_arfcn": 145600,
        "dl_mid_arfcn": 147400,
        "dl_high_arfcn": 149200,
        "ul_low_mhz": 698.0,
        "ul_mid_mhz": 707.0,
        "ul_high_mhz": 716.0,
        "ul_low_arfcn": 139600,
        "ul_mid_arfcn": 141400,
        "ul_high_arfcn": 143200,
        "duplex_spacing_mhz": 30.0,
        "equivalent_lte_band": "85",
        "area": "NAR",
        "release": "17.2",
        "note": None
    },
    {
        "band": "n86",
        "name": "UL n66",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 1710.0,
        "ul_mid_mhz": 1745.0,
        "ul_high_mhz": 1780.0,
        "ul_low_arfcn": 342000,
        "ul_mid_arfcn": 349000,
        "ul_high_arfcn": 356000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "66",
        "area": "NAR",
        "release": "15.2",
        "note": None
    },
    {
        "band": "n87",
        "name": "410",
        "mode": "FDD",
        "dl_low_mhz": 420.0,
        "dl_mid_mhz": 422.5,
        "dl_high_mhz": 425.0,
        "dl_low_arfcn": 84000,
        "dl_mid_arfcn": 84500,
        "dl_high_arfcn": 85000,
        "ul_low_mhz": 410.0,
        "ul_mid_mhz": 412.5,
        "ul_high_mhz": 415.0,
        "ul_low_arfcn": 82000,
        "ul_mid_arfcn": 82500,
        "ul_high_arfcn": 83000,
        "duplex_spacing_mhz": 10.0,
        "equivalent_lte_band": "87",
        "area": "EMEA",
        "release": "19.0",
        "note": None
    },
    {
        "band": "n88",
        "name": "410+",
        "mode": "FDD",
        "dl_low_mhz": 422.0,
        "dl_mid_mhz": 424.5,
        "dl_high_mhz": 427.0,
        "dl_low_arfcn": 84400,
        "dl_mid_arfcn": 84900,
        "dl_high_arfcn": 85400,
        "ul_low_mhz": 412.0,
        "ul_mid_mhz": 414.5,
        "ul_high_mhz": 417.0,
        "ul_low_arfcn": 82400,
        "ul_mid_arfcn": 82900,
        "ul_high_arfcn": 83400,
        "duplex_spacing_mhz": 10.0,
        "equivalent_lte_band": "88",
        "area": "EMEA",
        "release": "19.0",
        "note": None
    },
    {
        "band": "n89",
        "name": "UL n5",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 824.0,
        "ul_mid_mhz": 836.5,
        "ul_high_mhz": 849.0,
        "ul_low_arfcn": 164800,
        "ul_mid_arfcn": 167300,
        "ul_high_arfcn": 169800,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "5",
        "area": "NAR",
        "release": "16.1",
        "note": None
    },
    {
        "band": "n90",
        "name": "TD 2600+",
        "mode": "TDD",
        "dl_low_mhz": 2496.0,
        "dl_mid_mhz": 2593.0,
        "dl_high_mhz": 2690.0,
        "dl_low_arfcn": 499200,
        "dl_mid_arfcn": 518601,
        "dl_high_arfcn": 537999,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "41",
        "area": "Global",
        "release": "16.0",
        "note": None
    },
    {
        "band": "n91",
        "name": "FD 1500-",
        "mode": "FDD",
        "dl_low_mhz": 1427.0,
        "dl_mid_mhz": 1429.5,
        "dl_high_mhz": 1432.0,
        "dl_low_arfcn": 285400,
        "dl_mid_arfcn": 285900,
        "dl_high_arfcn": 286400,
        "ul_low_mhz": 832.0,
        "ul_mid_mhz": 847.0,
        "ul_high_mhz": 862.0,
        "ul_low_arfcn": 166400,
        "ul_mid_arfcn": 169400,
        "ul_high_arfcn": 172400,
        "duplex_spacing_mhz": 595.0,
        "equivalent_lte_band": None,
        "area": "NAR",
        "release": "16.2",
        "note": "10"
    },
    {
        "band": "n92",
        "name": "FD 1500+",
        "mode": "FDD",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1474.5,
        "dl_high_mhz": 1517.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 294900,
        "dl_high_arfcn": 303400,
        "ul_low_mhz": 832.0,
        "ul_mid_mhz": 847.0,
        "ul_high_mhz": 862.0,
        "ul_low_arfcn": 166400,
        "ul_mid_arfcn": 169400,
        "ul_high_arfcn": 172400,
        "duplex_spacing_mhz": 600.0,
        "equivalent_lte_band": None,
        "area": "NAR",
        "release": "16.2",
        "note": None
    },
    {
        "band": "n93",
        "name": "FD 1500-",
        "mode": "FDD",
        "dl_low_mhz": 1427.0,
        "dl_mid_mhz": 1429.5,
        "dl_high_mhz": 1432.0,
        "dl_low_arfcn": 285400,
        "dl_mid_arfcn": 285900,
        "dl_high_arfcn": 286400,
        "ul_low_mhz": 880.0,
        "ul_mid_mhz": 897.5,
        "ul_high_mhz": 915.0,
        "ul_low_arfcn": 176000,
        "ul_mid_arfcn": 179500,
        "ul_high_arfcn": 183000,
        "duplex_spacing_mhz": 547.0,
        "equivalent_lte_band": None,
        "area": "NAR",
        "release": "16.2",
        "note": "10"
    },
    {
        "band": "n94",
        "name": "FD 1500+",
        "mode": "FDD",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1474.5,
        "dl_high_mhz": 1517.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 294900,
        "dl_high_arfcn": 303400,
        "ul_low_mhz": 880.0,
        "ul_mid_mhz": 897.5,
        "ul_high_mhz": 915.0,
        "ul_low_arfcn": 176000,
        "ul_mid_arfcn": 179500,
        "ul_high_arfcn": 183000,
        "duplex_spacing_mhz": 552.0,
        "equivalent_lte_band": None,
        "area": "NAR",
        "release": "16.2",
        "note": None
    },
    {
        "band": "n95",
        "name": "UL n34",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 2010.0,
        "ul_mid_mhz": 2017.5,
        "ul_high_mhz": 2025.0,
        "ul_low_arfcn": 402000,
        "ul_mid_arfcn": 403500,
        "ul_high_arfcn": 405000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "34",
        "area": "China",
        "release": "16.2",
        "note": None
    },
    {
        "band": "n96",
        "name": "6Ghz",
        "mode": "TDD",
        "dl_low_mhz": 5925.0,
        "dl_mid_mhz": 6525.0,
        "dl_high_mhz": 7125.0,
        "dl_low_arfcn": 795000,
        "dl_mid_arfcn": 835000,
        "dl_high_arfcn": 875000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": "NAR",
        "release": "16.5",
        "note": None
    },
    {
        "band": "n97",
        "name": "UL n40",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 2300.0,
        "ul_mid_mhz": 2350.0,
        "ul_high_mhz": 2400.0,
        "ul_low_arfcn": 460000,
        "ul_mid_arfcn": 470000,
        "ul_high_arfcn": 480000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "40",
        "area": "APAC",
        "release": "17.0",
        "note": None
    },
    {
        "band": "n98",
        "name": "UL n39",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 1880.0,
        "ul_mid_mhz": 1900.0,
        "ul_high_mhz": 1920.0,
        "ul_low_arfcn": 376000,
        "ul_mid_arfcn": 380000,
        "ul_high_arfcn": 384000,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "39",
        "area": "China",
        "release": "17.0",
        "note": None
    },
    {
        "band": "n99",
        "name": "UL n24",
        "mode": "SUL",
        "dl_low_mhz": None,
        "dl_mid_mhz": None,
        "dl_high_mhz": None,
        "dl_low_arfcn": None,
        "dl_mid_arfcn": None,
        "dl_high_arfcn": None,
        "ul_low_mhz": 1626.5,
        "ul_mid_mhz": 1643.5,
        "ul_high_mhz": 1660.5,
        "ul_low_arfcn": 325300,
        "ul_mid_arfcn": 328700,
        "ul_high_arfcn": 332100,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": "24",
        "area": "NAR",
        "release": "17.1",
        "note": None
    },
    {
        "band": "n100",
        "name": "RMR 900",
        "mode": "FDD",
        "dl_low_mhz": 919.4,
        "dl_mid_mhz": 922.2,
        "dl_high_mhz": 925.0,
        "dl_low_arfcn": 183880,
        "dl_mid_arfcn": 184440,
        "dl_high_arfcn": 185000,
        "ul_low_mhz": 874.4,
        "ul_mid_mhz": 877.2,
        "ul_high_mhz": 880.0,
        "ul_low_arfcn": 174880,
        "ul_mid_arfcn": 175440,
        "ul_high_arfcn": 176000,
        "duplex_spacing_mhz": 45.0,
        "equivalent_lte_band": None,
        "area": None,
        "release": "17.6",
        "note": None
    },
    {
        "band": "n101",
        "name": "RMR 1900",
        "mode": "TDD",
        "dl_low_mhz": 1900.0,
        "dl_mid_mhz": 1905.0,
        "dl_high_mhz": 1910.0,
        "dl_low_arfcn": 380000,
        "dl_mid_arfcn": 381000,
        "dl_high_arfcn": 382000,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": None,
        "release": "17.5",
        "note": None
    },
    {
        "band": "n102",
        "name": "Lower 6GHz",
        "mode": "TDD",
        "dl_low_mhz": 5925.0,
        "dl_mid_mhz": 6175.0,
        "dl_high_mhz": 6425.0,
        "dl_low_arfcn": 795000,
        "dl_mid_arfcn": 811667,
        "dl_high_arfcn": 828333,
        "ul_low_mhz": None,
        "ul_mid_mhz": None,
        "ul_high_mhz": None,
        "ul_low_arfcn": None,
        "ul_mid_arfcn": None,
        "ul_high_arfcn": None,
        "duplex_spacing_mhz": None,
        "equivalent_lte_band": None,
        "area": None,
        "release": "17.5",
        "note": None
    },
    {
        "band": "n105",
        "name": "APT 600",
        "mode": "FDD",
        "dl_low_mhz": 612.0,
        "dl_mid_mhz": 632.0,
        "dl_high_mhz": 652.0,
        "dl_low_arfcn": 122400,
        "dl_mid_arfcn": 126400,
        "dl_high_arfcn": 130400,
        "ul_low_mhz": 663.0,
        "ul_mid_mhz": 683.0,
        "ul_high_mhz": 703.0,
        "ul_low_arfcn": 132600,
        "ul_mid_arfcn": 136600,
        "ul_high_arfcn": 140600,
        "duplex_spacing_mhz": -51.0,
        "equivalent_lte_band": None,
        "area": None,
        "release": "18.0",
        "note": "3"
    },
    {
        "band": "n106",
        "name": "900",
        "mode": "FDD",
        "dl_low_mhz": 935.0,
        "dl_mid_mhz": 937.5,
        "dl_high_mhz": 940.0,
        "dl_low_arfcn": 187000,
        "dl_mid_arfcn": 187500,
        "dl_high_arfcn": 188000,
        "ul_low_mhz": 896.0,
        "ul_mid_mhz": 898.5,
        "ul_high_mhz": 901.0,
        "ul_low_arfcn": 179200,
        "ul_mid_arfcn": 179700,
        "ul_high_arfcn": 180200,
        "duplex_spacing_mhz": 39.0,
        "equivalent_lte_band": "106",
        "area": None,
        "release": "18.4",
        "note": None
    },
    {
        "band": "n109",
        "name": "1500",
        "mode": "FDD",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1474.5,
        "dl_high_mhz": 1517.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 294900,
        "dl_high_arfcn": 303400,
        "ul_low_mhz": 703.0,
        "ul_mid_mhz": 718.0,
        "ul_high_mhz": 733.0,
        "ul_low_arfcn": 140600,
        "ul_mid_arfcn": 143600,
        "ul_high_arfcn": 146600,
        "duplex_spacing_mhz": 729.0,
        "equivalent_lte_band": None,
        "area": None,
        "release": "18.4",
        "note": "6"
    },
    {
        "band": "n110",
        "name": "1500-",
        "mode": "FDD",
        "dl_low_mhz": 1432.0,
        "dl_mid_mhz": 1433.5,
        "dl_high_mhz": 1435.0,
        "dl_low_arfcn": 286400,
        "dl_mid_arfcn": 286700,
        "dl_high_arfcn": 287000,
        "ul_low_mhz": 1390.0,
        "ul_mid_mhz": 1392.5,
        "ul_high_mhz": 1395.0,
        "ul_low_arfcn": 278000,
        "ul_mid_arfcn": 278500,
        "ul_high_arfcn": 279000,
        "duplex_spacing_mhz": 42.0,
        "equivalent_lte_band": None,
        "area": None,
        "release": "19.0",
        "note": None
    },
    {
        "band": "n256",
        "name": "NTN 2000",
        "mode": "FDD",
        "dl_low_mhz": 2170.0,
        "dl_mid_mhz": 2185.0,
        "dl_high_mhz": 2200.0,
        "dl_low_arfcn": 434000,
        "dl_mid_arfcn": 437000,
        "dl_high_arfcn": 440000,
        "ul_low_mhz": 1980.0,
        "ul_mid_mhz": 1995.0,
        "ul_high_mhz": 2010.0,
        "ul_low_arfcn": 396000,
        "ul_mid_arfcn": 399000,
        "ul_high_arfcn": 402000,
        "duplex_spacing_mhz": 190.0,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "17.0",
        "note": "NTN"
    },
    {
        "band": "n255",
        "name": "NTN 1600",
        "mode": "FDD",
        "dl_low_mhz": 1525.0,
        "dl_mid_mhz": 1542.0,
        "dl_high_mhz": 1559.0,
        "dl_low_arfcn": 305000,
        "dl_mid_arfcn": 308400,
        "dl_high_arfcn": 311800,
        "ul_low_mhz": 1626.5,
        "ul_mid_mhz": 1643.5,
        "ul_high_mhz": 1660.5,
        "ul_low_arfcn": 325300,
        "ul_mid_arfcn": 328700,
        "ul_high_arfcn": 332100,
        "duplex_spacing_mhz": -101.5,
        "equivalent_lte_band": "24",
        "area": "NTN",
        "release": "17.0",
        "note": "NTN"
    },
    {
        "band": "n254",
        "name": "NTN 1600+",
        "mode": "FDD",
        "dl_low_mhz": 2483.5,
        "dl_mid_mhz": 2491.8,
        "dl_high_mhz": 2500.0,
        "dl_low_arfcn": 496700,
        "dl_mid_arfcn": 498360,
        "dl_high_arfcn": 500000,
        "ul_low_mhz": 1610.0,
        "ul_mid_mhz": 1618.3,
        "ul_high_mhz": 1626.5,
        "ul_low_arfcn": 322000,
        "ul_mid_arfcn": 323650,
        "ul_high_arfcn": 325300,
        "duplex_spacing_mhz": 873.5,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "18.4",
        "note": "NTN"
    },
    {
        "band": "n253",
        "name": "NTN 1600",
        "mode": "FDD",
        "dl_low_mhz": 1518.0,
        "dl_mid_mhz": 1521.5,
        "dl_high_mhz": 1525.0,
        "dl_low_arfcn": 303600,
        "dl_mid_arfcn": 304300,
        "dl_high_arfcn": 305000,
        "ul_low_mhz": 1668.0,
        "ul_mid_mhz": 1671.5,
        "ul_high_mhz": 1675.0,
        "ul_low_arfcn": 333600,
        "ul_mid_arfcn": 334300,
        "ul_high_arfcn": 335000,
        "duplex_spacing_mhz": -150.0,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "19.2",
        "note": "NTN"
    },
    {
        "band": "n252",
        "name": "NTN 2000+",
        "mode": "FDD",
        "dl_low_mhz": 2180.0,
        "dl_mid_mhz": 2190.0,
        "dl_high_mhz": 2200.0,
        "dl_low_arfcn": 436000,
        "dl_mid_arfcn": 438000,
        "dl_high_arfcn": 440000,
        "ul_low_mhz": 2000.0,
        "ul_mid_mhz": 2010.0,
        "ul_high_mhz": 2020.0,
        "ul_low_arfcn": 400000,
        "ul_mid_arfcn": 402000,
        "ul_high_arfcn": 404000,
        "duplex_spacing_mhz": 180.0,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "19.1",
        "note": "NTN"
    },
    {
        "band": "n251",
        "name": "NTN 1600",
        "mode": "FDD",
        "dl_low_mhz": 1518.0,
        "dl_mid_mhz": 1538.5,
        "dl_high_mhz": 1559.0,
        "dl_low_arfcn": 303600,
        "dl_mid_arfcn": 307700,
        "dl_high_arfcn": 311800,
        "ul_low_mhz": 1626.5,
        "ul_mid_mhz": 1650.8,
        "ul_high_mhz": 1675.0,
        "ul_low_arfcn": 333600,
        "ul_mid_arfcn": 334300,
        "ul_high_arfcn": 335000,
        "duplex_spacing_mhz": -108.5,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "19.2",
        "note": "NTN"
    },
    {
        "band": "n250",
        "name": "NTN 1600",
        "mode": "FDD",
        "dl_low_mhz": 1518.0,
        "dl_mid_mhz": 1538.5,
        "dl_high_mhz": 1559.0,
        "dl_low_arfcn": 303600,
        "dl_mid_arfcn": 307700,
        "dl_high_arfcn": 311800,
        "ul_low_mhz": 1626.5,
        "ul_mid_mhz": 1643.5,
        "ul_high_mhz": 1660.5,
        "ul_low_arfcn": 325300,
        "ul_mid_arfcn": 328700,
        "ul_high_arfcn": 332100,
        "duplex_spacing_mhz": -108.5,
        "equivalent_lte_band": None,
        "area": "NTN",
        "release": "19.2",
        "note": "NTN"
    }
]


def _is_between(value: float, low: float | None, high: float | None) -> bool:
    if low is None or high is None:
        return False

    return low <= value <= high


def frequency_to_nr_arfcn(frequency_mhz: float) -> int | None:
    """Convert frequency in MHz to global NR-ARFCN as a fallback."""

    if frequency_mhz < 0:
        return None

    if frequency_mhz < 3000:
        return int(round(frequency_mhz / 0.005))

    if frequency_mhz < 24250:
        return int(round(600000 + ((frequency_mhz - 3000) / 0.015)))

    return None


def _arfcn_from_points(
    frequency_mhz: float,
    points: list[tuple[float | None, int | None]],
) -> int | None:
    clean_points = [
        (float(freq), int(arfcn))
        for freq, arfcn in points
        if freq is not None and arfcn is not None
    ]

    if not clean_points:
        return frequency_to_nr_arfcn(frequency_mhz)

    for freq, arfcn in clean_points:
        if abs(frequency_mhz - freq) < 1e-9:
            return arfcn

    clean_points.sort(key=lambda item: item[0])

    for (freq_a, arfcn_a), (freq_b, arfcn_b) in zip(
        clean_points,
        clean_points[1:],
    ):
        if freq_a <= frequency_mhz <= freq_b and freq_b != freq_a:
            ratio = (frequency_mhz - freq_a) / (freq_b - freq_a)
            return int(round(arfcn_a + ratio * (arfcn_b - arfcn_a)))

    return frequency_to_nr_arfcn(frequency_mhz)


def _band_arfcn(
    band: dict[str, Any],
    frequency_mhz: float | None,
    direction: str,
) -> int | None:
    if frequency_mhz is None:
        return None

    prefix = "ul" if direction == "UL" else "dl"

    return _arfcn_from_points(
        frequency_mhz,
        [
            (band.get(f"{prefix}_low_mhz"), band.get(f"{prefix}_low_arfcn")),
            (band.get(f"{prefix}_mid_mhz"), band.get(f"{prefix}_mid_arfcn")),
            (band.get(f"{prefix}_high_mhz"), band.get(f"{prefix}_high_arfcn")),
        ],
    )


def _round_mhz(value: float | None) -> float | None:
    if value is None:
        return None

    return round(float(value), 6)


def _build_result(
    *,
    band: dict[str, Any],
    detected_frequency_mhz: float,
    direction: str,
    freq_dl_mhz: float | None,
    freq_ul_mhz: float | None,
) -> dict[str, Any]:
    nr_arfcn_dl = _band_arfcn(band, freq_dl_mhz, "DL")
    nr_arfcn_ul = _band_arfcn(band, freq_ul_mhz, "UL")

    if direction in {"DL", "SDL", "TDD"}:
        nr_arfcn = nr_arfcn_dl
    elif direction in {"UL", "SUL"}:
        nr_arfcn = nr_arfcn_ul
    else:
        nr_arfcn = frequency_to_nr_arfcn(detected_frequency_mhz)

    return {
        "technology": "5G NR",
        "band": band["band"],
        "band_code": band["band"],
        "name": f"{band['band']} {band['name']}",
        "band_name": band["name"],
        "mode": band["mode"],
        "direction": direction,
        "freq_mhz": _round_mhz(detected_frequency_mhz),
        "freq_dl_mhz": _round_mhz(freq_dl_mhz),
        "freq_ul_mhz": _round_mhz(freq_ul_mhz),
        "nr_arfcn": nr_arfcn,
        "nr_arfcn_dl": nr_arfcn_dl,
        "nr_arfcn_ul": nr_arfcn_ul,
        "area": band.get("area"),
        "release": band.get("release"),
        "note": band.get("note"),
    }


def classify_nr(frequency_mhz: float) -> list[dict[str, Any]]:
    """Return possible 5G NR FR1 candidates for a frequency in MHz."""

    freq = float(frequency_mhz)
    candidates: list[dict[str, Any]] = []

    for band in NR_FR1_BANDS:
        mode = band["mode"]
        dl_low = band.get("dl_low_mhz")
        dl_high = band.get("dl_high_mhz")
        ul_low = band.get("ul_low_mhz")
        ul_high = band.get("ul_high_mhz")
        duplex_spacing = band.get("duplex_spacing_mhz")

        if mode == "TDD" and _is_between(freq, dl_low, dl_high):
            candidates.append(
                _build_result(
                    band=band,
                    detected_frequency_mhz=freq,
                    direction="TDD",
                    freq_dl_mhz=freq,
                    freq_ul_mhz=freq,
                )
            )
            continue

        if mode == "SDL" and _is_between(freq, dl_low, dl_high):
            candidates.append(
                _build_result(
                    band=band,
                    detected_frequency_mhz=freq,
                    direction="SDL",
                    freq_dl_mhz=freq,
                    freq_ul_mhz=None,
                )
            )
            continue

        if mode == "SUL" and _is_between(freq, ul_low, ul_high):
            candidates.append(
                _build_result(
                    band=band,
                    detected_frequency_mhz=freq,
                    direction="SUL",
                    freq_dl_mhz=None,
                    freq_ul_mhz=freq,
                )
            )
            continue

        if mode != "FDD":
            continue

        if _is_between(freq, dl_low, dl_high):
            paired_ul_mhz = None

            if duplex_spacing is not None:
                possible_ul = freq - float(duplex_spacing)

                if _is_between(possible_ul, ul_low, ul_high):
                    paired_ul_mhz = possible_ul

            candidates.append(
                _build_result(
                    band=band,
                    detected_frequency_mhz=freq,
                    direction="DL",
                    freq_dl_mhz=freq,
                    freq_ul_mhz=paired_ul_mhz,
                )
            )

        if _is_between(freq, ul_low, ul_high):
            paired_dl_mhz = None

            if duplex_spacing is not None:
                possible_dl = freq + float(duplex_spacing)

                if _is_between(possible_dl, dl_low, dl_high):
                    paired_dl_mhz = possible_dl

            candidates.append(
                _build_result(
                    band=band,
                    detected_frequency_mhz=freq,
                    direction="UL",
                    freq_dl_mhz=paired_dl_mhz,
                    freq_ul_mhz=freq,
                )
            )

    return candidates
